export const texts = {
  en: {
    h1: "Site Under Construction",
    h_about: "About",
    p_about: [
      `I love my life and the journey I've taken so far,(I love my life and the path I have walked on so far) and even though I've been down ( in my life ) more than once ( and have reached the rock bottom ), (I have found myself down and at the bottom more than once)every moment has had its meaning and I'm grateful for it. For over 20 years, my passion has been exploring different holistic therapeutic approaches and methods that can enable us to live in harmony and joy. (if we allow it..) (if we allow ourselves to..)`,
      `In my frequent travels to remote and beautiful places in the world, I realized that there are no coincidences or accidents and what happens to us in our life is always a message from Life (God, the Universe, etc. we all perceive "it" differently...) A message, with which it is possible to work (A message that can be worked with) and if we learn how to understand those messages of Life, we will receive (we are given) a wonderful tool (how to achieve) to live in harmony, contentment and love.`,
      `For many years I lived in beautiful and interesting places in the world, which influenced me with their unique energy and helped me to connect with my inner self and with who I am and what I am doing here. I also understood what and why is happening in my life and that I create my own reality (myself) and I no longer have to be a victim of destiny(fate), programs from childhood, family patterns etc., but a creator who knows that we did not come into the world to suffer, but to live in joy, to explore and learn. Music and dance have also helped me to connect with my inner world all my life. I play the oriental frame drum and sing, the rhythm and amazing sound of the drum is a beautiful and healing gift for which I am very grateful.`,
    ],
    h_kranio: "Cranioshacral therapy",
    p_kranio: [`Paragraph about kranio`],
    name: "Name:",
    namePh: "Your name",
    subject: "Subject:",
    subjectPh: "Subject",
    message: "Message:",
    messagePh: "Your message",
    sending: "Sending message...",
    success: "Message sent successfully!",
    error: "Error sending message:",
    links: [
      { id: 1, url: "", text: "Home" },
      { id: 2, url: "about", text: "About" },
      { id: 3, url: "kranio", text: "Cranioshacral therapy" },
      { id: 4, url: "qualification", text: "Qualification" },
      { id: 5, url: "pricelist", text: "Pricelist" },
      { id: 6, url: "contact", text: "Contact" },
    ],
  },
  cz: {
    h1: "Web Ve Výstavbě",
    h_about: "O mně",
    p_about: [
      `Miluji svůj život a cestu, kterou jsem ušla (po které jdu), a i když jsem se nejednou ocitla na pomyslném dně, každý okamžik měl svůj význam a jsem za něj vděčná. Přes 20 let je mou vášní zkoumání různých celostních terapeutických přístupů a metod, které nám mohou umožnit žít v harmonii a radosti. (pokud si to dovolíme..)`,
      `Na svých cestách po odlehlých a krásných místech světa, jsem si uvědomila, že náhody ani nehody neexistují, že to co se nám v životě děje, je vždy vzkazem od Života ( Boha, Vesmíru, každý “to” vnímáme jinak..) Vzkazem, se kterým je možné pracovat a pokud se naučíme rozumět řeči a vzkazům Života, dostaneme úžasný nástroj k tomu, jak žít v harmonii, spokojenosti a lásce. `,
      `Dlouhá léta jsem žila na krásných a zajímavých místech světa, která mne ovlivnila svou jedinečnou energií a pomohla mi se propojit sama se sebou, s tím kdo jsem a co tu dělám. pochopila jsem také co a proč se mi v životě děje a že si svou vlastní realitu tvořím sama a už nemusím být obětí osudu, programů z dětství, rodinných vzorců apod., ale tvůrcem, který ví, že na svět nepřišel trpět, ale radovat se, poznávat a učit se. K propojení se s mým vnitřním světem mi celý život pomáha i hudba a tanec. Hraju na orientální rámový buben a zpívám, rytmus a úžasný zvuk bubnu je krásný a léčebný dar, za který jsem moc vděčná.`,
    ],
    h_kranio: "Kraniosakrální terapie",
    p_kranio: [`Odstavec o kranio`],
    name: "Jméno:",
    namePh: "Jméno",
    subject: "Předmět:",
    subjectPh: "Předmět",
    message: "Zpráva",
    messagePh: "Vaše zpráva",
    sending: "Odesílání zprávy...",
    success: "Zpráva úspěšně odeslána!",
    error: "Chyba při odesílání zprávy:",
    links: [
      { id: 1, url: "", text: "Doma" },
      { id: 2, url: "about", text: "O mně" },
      { id: 3, url: "kranio", text: "Kraniosakrální terapie" },
      { id: 4, url: "qualification", text: "Kvalifikace" },
      { id: 5, url: "pricelist", text: "Ceník" },
      { id: 6, url: "contact", text: "Kontakt" },
    ],
  },
};
