export const texts = {
  common: {
    address_l1: "Sládkova 262/7, 170 00 Praha 7",
    address_l2: "Bubeneč (v těsné blízkosti Letenského nám.)",
    telephone: "+420 775 232 633",
    email: "info@sakara.cz",
  },
  en: {
    home: {
      descr: "Cranioshacral therapy and consaltation",
    },
    h1: "Site Under Construction",
    h_about: "About",
    p_about: [
      `I love my life and the journey I've taken so far and even though I've been down in my life more than once and have reached the rock bottom, every moment has had its meaning and I'm grateful for it. For over 15 years, my passion has been exploring different holistic therapeutic approaches and methods that can enable us to live in harmony and joy. In my frequent travels to remote and beautiful places in the world, I realized that there are no coincidences or accidents and what happens to us in our life is a message from Life - God, the Universe, etc. we all perceive "IT" differently. A message that can be worked with and if we learn how to understand those messages of Life, we will receive a wonderful tool how to achieve to live in harmony, contentment and love. Sometimes these messages are quite hard to understand and I have found excellent help precisely in therapies that can help us with the "translation".`,
      `The important men in my life, my father and my husband, both come from the Balkans, to which I am also connected, especially with my old and exceptional friend - the sea. The sea, on whose shores one can feel unity and non-duality, the sea is neither good nor bad, the sea just is. The sea, which was an important part of my childhood and always helped me to calm down internally and realize that there is something present with us that we are not able to understand with our minds, and that it is something beyond everything we know and comprehend.`,
      `For many years I lived in beautiful and interesting places in the world, which influenced me with their unique energy and helped me to connect with my inner self and with who I am and what I am doing here. I also understood what and why is happening in my life and that I create my own reality and I no longer have to be a victim of destiny, programs from childhood, family patterns etc., but a creator who knows that we did not come into the world to suffer, but to live in joy, to explore and learn. Music and dance have also helped me to connect with my inner world all my life. I play the oriental frame drum and sing, the rhythm and amazing sound of the drum is a beautiful and healing gift for which I am very grateful.`,
    ],
    h_kranio: "Cranioshacral therapy",
    p_kranio: [
      `Craniosacral Therapy (CST) is a gentle, hands-on method of evaluating and enhancing the functioning of a physiological body system called the craniosacral system - comprised of the membranes and cerebrospinal fluid that surround and protect the brain and spinal cord. Using a soft touch generally no greater than 5 grams, practitioners release restrictions in the craniosacral system, which has been shown to improve the functioning of the central nervous system, as well as many other systems of the body, such as digestive, musculoskeletal, respiratory, circulatory, and more. CST has also been shown to help with the physical components related to such somatic conditions as Post Traumatic Stress, depression and anxiety.`,
      `By facilitating the body's natural and innate healing processes, CST is increasingly used as a preventive health measure for its ability to bolster resistance to disease, and has been shown to be beneficial for people seeking help with a wide range of healthcare challenges and symptoms.`,
    ],
    ul_kranio: [
      {
        title: "A few examples of what CST is suitable for:",
        items: [
          "Migraines and headaches",
          "Chronic pain",
          "Motor-Coordination impairments",
          "Central nervous system disorders",
          "Orthopedic problems",
          "Traumatic brain injuries and concussions",
          "Alzheimer's",
          "Spinal Cord Injuries",
          "Scoliosis",
          "Conception, pregnancy, birth",
          "Pediatric challenges",
          "Learning differences, ADD, ADHD",
          "Autism and sensory processing",
          "Chronic fatigue",
          "Emotional difficulties, depression",
          "Stress and tension-related problems",
          "Fibromyalgia and other Connective-Tissue Disorders",
          "Temporomandibular Joint Syndrome (TMJ) and Dental Challenges",
          "Immune Disorders",
          "Post-Traumatic Stress Disorder",
          "Post-Surgical Dysfunction",
          "Sleep Challenges",
          "and many more..",
        ],
      },
      {
        title: "A few examples of what happens during Craniosacral Therapy (CST)",
        items: [
          "Release of tissue tension, fascia, muscles, and joints",
          "Stretching of spinal ligaments",
          "Release and harmonization of organs, diaphragm, and connective tissues",
          "Improvement of fluid flow in the body",
          "Regulation of an overloaded nervous system (transition from sympathetic to parasympathetic)",
          "and many more..",
        ],
      },
    ],
    h_qualification: "Qualification",
    core_qualification: {
      description: "Výcvik v kraniosakrální terapii - Radek Neškrabal",
      items: [
        {
          title: "Ošetření příčných struktur",
          text: "(historie a principy kraniosakrální osteopatie, anatomie a fyziologie kraniosakrálního systému, etika přístupu ke klientovi, základy psychohygieny, teorie a praxe palpace kraniosakrálního rytmu, anatomie a ošetření příčných struktur, dekomprese kosti křížové, teorie a praxe práce se spinální durou mater, útlum kraniosakrálního systému CV4)",
        },
        {
          title: "Neurocranium",
          text: "(prohloubení dovedností práce s kraniosakrálním rytmem, anatomie a fyziologie kraniosakrálního rytmu na lebce, teorie a praxe dekomprese jednotlivých lebečních kostí: frontální, parietální, SSB, temporální, temporomandibulární kloub)",
        },
        {
          title: "SSB + membránový systém",
          text: "(anatomie a fyziologie kraniálního rytmu na SSB, teorie a praxe vyšetření a ošetření 11 lézí SSB, anatomie a fyziologie kraniálního rytmu na membránovém systému, palpace a sledování rytmu na membránovém systému, ošetření membránového systému)",
        },
        {
          title: "Viscerocranium, energetický přístup ",
          text: "(anatomie a fyziologie kraniálního rytmu na horním patře a obličejové části, vyšetření a ošetření komplexu sphenoid-maxilla-vomer-palatinum, ošetření obličejové části – zygomaticum, vyšetření a ošetření zubů, mentální detoxikace, detoxikace organismu, práce s energií - V spred)",
        },
        {
          title: "Drenáž žilních splavů, komorový systém, EV 4",
          text: "(anatomie žilních splavů, fyziologie žilních splavů, symptomy chorob, anatomie mozkových komor, fyziologie mozkových komor)",
        },
        {
          title: "Tělo a emoce",
          text: "(vymezení působnosti podpůrného dialogu, etika přístupu v interakci s klientem, základy teorie psychoterapeutických přístupů, praktická cvičení, práce se zdroji, vtělení zdrojů, pociťovaný smysl, hranice a jejich rozpoznání, verbální a neverbální komunikace, stres a trauma, jak vzniká, jak ho poznat a jak předejít retraumatizaci, somatoemocionální uvolnění – teorie – praktická cvičení, cvičení ve vedení praxe s verbální podporou)",
        },
      ],
    },
    other_qualification: {
      description: "Other Qualification",
      items: [
        { title: "Výcvik v hypnosystemické terapii - Bhagat J. Zeilhofer", text: "" },
        { title: "Nadstavbový seminář: Nervus Vagus a polyvagalní přístupy v CST – Inka Tichá", text: "" },
        { title: "Webinář: Osrdečník - Etienne Peirsman", text: "" },
        {
          title:
            "Webinář: Traumata z porodu v kojeneckém věku a pozdějším dětství, Co nás děti učí o nás samotných - Matthew Appleto",
          text: "",
        },
        { title: "Seminář: Lymfodrenážní masáž - Boris Tichanovský", text: "" },
        { title: "Reiki - Boris Tichanovský", text: "" },
        { title: "Reiki - Iva Kukačková", text: "" },
      ],
    },
    h_reviews: "Reviews",
    h_pricelist: "Pricelist",
    p_pricelist: {
      price: "CST and consultation 90 min. / 1400,-Kč",
      cancelation:
        "If the appointment is canceled on the day of the agreed reservation, a fee of 50% of the therapy price is charged, with the exception of emergency reasons.",
      other_option: "In exceptional cases, contact me and we will agree on a price.",
    },
    h_contact: "Contact",
    name: "Name:",
    namePh: "Your name",
    subject: "Subject:",
    subjectPh: "Subject",
    message: "Message:",
    messagePh: "Your message",
    sending: "Sending message...",
    success: "Message sent successfully!",
    error: "Error sending message:",
    links: [
      { id: 1, url: "home", text: "Home" },
      { id: 2, url: "about", text: "About" },
      { id: 3, url: "qualification", text: "Qualification" },
      { id: 4, url: "kranio", text: "Cranioshacral therapy" },
      { id: 5, url: "reviews", text: "Reviews" },
      { id: 6, url: "pricelist", text: "Pricelist" },
      { id: 7, url: "contact", text: "Contact" },
    ],
  },
  cz: {
    home: {
      descr: "Kraniosakrální terapie a konzultace",
    },
    h1: "Web Ve Výstavbě",
    h_about: "O mně",
    p_about: [
      `Miluji svůj život, cestu po které jdu, a i když jsem se nejednou ocitla na pomyslném dně, každý okamžik měl svůj význam a jsem za něj vděčná. Přes 15 let je mou vášní zkoumání různých celostních terapeutických přístupů a metod, které nám mohou umožnit žít v harmonii a radosti. Na svých cestách po odlehlých a krásných místech světa, jsem si uvědomila, že náhody ani nehody neexistují, že to co se mi v životě děje, je vzkazem od Života – Boha, Vesmíru, každý “TO” vnímáme jinak. Vzkazem, se kterým je možné pracovat a pokud se naučíme rozumět řeči a vzkazům Života, dostaneme úžasný nástroj k tomu, jak žít v harmonii, spokojenosti a lásce. Někdy jsou tyto vzkazy dost nesrozumitelné a já jsem našla výbornou pomoc právě v terapiích, které nám mohou s “překladem” pomoci. Jednou z takovýchto úžasných metod je kraniosakrální terapie, která nám pomáhá se propojit se Zdravím, které je přítomné v každém z nás a za všech okolností.`,
      `Důležití muži mého života, můj otec a můj muž, jsou oba z Balkánu, s kterým jsem propojená i já a zvláště pak s mým odvěkým a vyjímečným přítelem a tím je moře. Moře, na jehož břehu je možné zavnímat jednotu a nedualitu, moře není ani hodné ani zlé, moře jen je. Moře, které bylo důležitou součástí mého dětství a které mi vždy pomáhalo se vnitřně zklidnit a zavnímat, že je tu s námi přítomno něco, co nejsme schopni pochopit svou myslí a že to něco přesahuje vše co známe a je to tak dobře.`,
      `Dlouhá léta jsem žila na krásných a zajímavých místech světa, která mne ovlivnila svou jedinečnou energií a pomohla mi se propojit sama se sebou, s tím kdo jsem a co tu dělám a pochopit, že je důležité žít co nejvíce v přítomnosti, svými myšlenkami tady a teď, si tvoříme budoucnost a je na nás, jak bude vypadat. Pochopila jsem, že si svou vlastní realitu tvořím z největší části sama a už nemusím být obětí osudu, programů z dětství, rodinných vzorců apod., ale tvůrcem, který ví, že na svět nepřišel trpět, ale radovat se, poznávat a učit se. K propojení se s mým vnitřním světem mi celý život pomáha i hudba a tanec. Hraju na orientální rámový buben a zpívám, rytmus a úžasný zvuk bubnu je krásný a léčebný dar, za který jsem moc vděčná.`,
    ],
    h_kranio: "Kraniosakrální terapie",
    p_kranio: [
      `Kraniosakrální terapie (KST) je jemná doteková metoda, která podporuje znovunalezení rovnováhy a harmonie a pomáhá nám se propojit se Zdravím, které je přítomné v každém z nás. Pracuje s naším fyzickým, psychickým i emočním tělem a tím ovlivňuje opravdu širokou škálu obtíží. Je to celostní metoda, která se zaměřuje na pravou příčinu problému, výborně reguluje přetížený nervový systém, ulevuje obtížím pohybového aparátu, výborně pracuje s traumaty, s obtížemi po úrazech a operacích a v neposlední řadě s obtížemi spojenými se stresem, který je v naší tzv.civilizované společnosti už zcela běžnou součástí našich životů. Ošetření nastartuje léčebný proces, který působí delší dobu po samotném setkání. Dlouhodobější praxe kraniosakrální terapie pomáhá nastolit trvalejší propojení mezi naším tělem, myslí a duší. Pomáhá nám propojit se s našim nitrem a zkontaktovat se s hlubokým vnitřním klidem, který je zásadní pro samoléčebné procesy, kterých je naše tělo schopné, pokud k tomu má vhodné podmínky. KST se také stále více používá jako preventivní zdravotní opatření pro svou schopnost posílit odolnost vůči nemocem všeho druhu.`,
      `Kraniosakrální terapie je vhodná v jakémkoliv věku a pro opravdu širokou škálu klientů. Vzhledem k její jemnosti a integrujícímu působení je možné ji mimo jiné doporučit i pro práci s miminky po porodu, pro těhotné ženy, je možné pracovat s dětmi, dospívajícími, dospělými i seniory a může být i velmi vhodnou podporující praxí pro umírající.`,
      `Pomáhá nám propojit se se svými potřebami, objevit respekt vůči svému tělu a získat nadhled v každodenních situacích. Níže uvádím pár příkladů na co se KST zaměřuje a s čím mimo jiné pracuje. Pokud se chcete dozvědět více o této úžasné holistické metodě, její historii a účincích, podívejte se na www.kranio.eu.`,
      `Při KST se dostáváme do kontaktu s podstatou lidské existence. To je významné z několika důvodů. Na fyzické úrovni navazujeme vztah s fyziologickým jádrem těla, které má na starost souhru všech tělesných funkcí. Na úrovni psychiky, se dostáváme do kontaktu s psychologickým jádrem, tzn.tím jak zpracováváme naše zkušenosti a jak se vztahujeme k minulosti. A konečně se dostáváme do kontaktu i s duchovní podstatou rezonující se smyslem života jako takového.`,
    ],
    ul_kranio: [
      {
        title: "Pár příkladů na co je KST vhodná",
        items: [
          "při chronických i akutních bolestech",
          "ulevuje obtížím pohybového aparátu, bolesti zad, kloubů, skolióza apod.",
          "bolesti hlavy, migrény",
          "pomáhá se zpracováním traumat",
          "deprese, problémy související se stresem a napětím, posttraumatická stresová porucha, psychické obtíže",
          "pro rychlejší hojení po úrazech, operacích a dlouhodobých onemocněních",
          "pomáhá při psychosomatických obtížích",
          "ideální pro podoru imunitního systému",
          "výborně funguje jako podpora a příprava na porod a poporodní období",
          "poruchy centrálního nervového systému, neuralgie, neurodegenerativní onemocnění, poruchy řeči",
          "příznivě ovlivnuje činnost srdce, oběhového, dychacího, hormonálního systému atd.",
          "autismus, ADHD, ADD, unavový syndrom, nespavost, vyčerpanost, pocit přetížení",
          "podpora při Alzheimerově chorobě, epilepsii, roztroušené skleróze",
          "opakované záněty v těle",
          "k zvýšení kapacity energie a vitality",
          "k celistvějšímu vnímání těla",
          "k nastartování samoléčebných procesů v těle",
          "pomáhá zvládat těžké životní situace",
          "a mnoho dalších",
        ],
      },
      {
        title: "Pár příkladů toho co se děje při KST",
        items: [
          "dochází k uvolnění napětí tkání, fascií, svalů a kloubů",
          "k protahování vazů páteře",
          "k uvolnění a harmonizaci orgánů, bránice a pojivových tkání",
          "k zlepšení průtoku tekutin v těle",
          "k regulaci přetíženého nervového systému ( přechod ze sympatiku do parasympatiku ) atd.",
        ],
      },
    ],
    h_qualification: "Kvalifikace",
    core_qualification: {
      description: "Výcvik v kraniosakrální terapii - Radek Neškrabal",
      items: [
        {
          title: "Ošetření příčných struktur",
          text: "(historie a principy kraniosakrální osteopatie, anatomie a fyziologie kraniosakrálního systému, etika přístupu ke klientovi, základy psychohygieny, teorie a praxe palpace kraniosakrálního rytmu, anatomie a ošetření příčných struktur, dekomprese kosti křížové, teorie a praxe práce se spinální durou mater, útlum kraniosakrálního systému CV4)",
        },
        {
          title: "Neurocranium",
          text: "(prohloubení dovedností práce s kraniosakrálním rytmem, anatomie a fyziologie kraniosakrálního rytmu na lebce, teorie a praxe dekomprese jednotlivých lebečních kostí: frontální, parietální, SSB, temporální, temporomandibulární kloub)",
        },
        {
          title: "SSB + membránový systém",
          text: "(anatomie a fyziologie kraniálního rytmu na SSB, teorie a praxe vyšetření a ošetření 11 lézí SSB, anatomie a fyziologie kraniálního rytmu na membránovém systému, palpace a sledování rytmu na membránovém systému, ošetření membránového systému)",
        },
        {
          title: "Viscerocranium, energetický přístup ",
          text: "(anatomie a fyziologie kraniálního rytmu na horním patře a obličejové části, vyšetření a ošetření komplexu sphenoid-maxilla-vomer-palatinum, ošetření obličejové části – zygomaticum, vyšetření a ošetření zubů, mentální detoxikace, detoxikace organismu, práce s energií - V spred)",
        },
        {
          title: "Drenáž žilních splavů, komorový systém, EV 4",
          text: "(anatomie žilních splavů, fyziologie žilních splavů, symptomy chorob, anatomie mozkových komor, fyziologie mozkových komor)",
        },
        {
          title: "Tělo a emoce",
          text: "(vymezení působnosti podpůrného dialogu, etika přístupu v interakci s klientem, základy teorie psychoterapeutických přístupů, praktická cvičení, práce se zdroji, vtělení zdrojů, pociťovaný smysl, hranice a jejich rozpoznání, verbální a neverbální komunikace, stres a trauma, jak vzniká, jak ho poznat a jak předejít retraumatizaci, somatoemocionální uvolnění – teorie – praktická cvičení, cvičení ve vedení praxe s verbální podporou)",
        },
      ],
    },
    other_qualification: {
      description: "Další kvalifikace",
      items: [
        { title: "Výcvik v hypnosystemické terapii - Bhagat J. Zeilhofer", text: "" },
        { title: "Nadstavbový seminář: Nervus Vagus a polyvagalní přístupy v CST – Inka Tichá", text: "" },
        { title: "Webinář: Osrdečník - Etienne Peirsman", text: "" },
        {
          title:
            "Webinář: Traumata z porodu v kojeneckém věku a pozdějším dětství, Co nás děti učí o nás samotných - Matthew Appleto",
          text: "",
        },
        { title: "Seminář: Lymfodrenážní masáž - Boris Tichanovský", text: "" },
        { title: "Reiki - Boris Tichanovský", text: "" },
        { title: "Reiki - Iva Kukačková", text: "" },
      ],
    },
    h_reviews: "Recenze",
    h_pricelist: "Ceník",
    p_pricelist: {
      price: "KST a konzultace 90 min. / 1400,-Kč",
      cancelation:
        "Při zrušení termínu v den domluvené rezervace je účtován poplatek 50% z ceny terapie, s vyjímkou akutních důvodů.",
      other_option: "Ve vyjímečných případech mne kontaktujte a na ceně se dohodneme.",
    },
    h_contact: "Kontakt",
    name: "Jméno:",
    namePh: "Jméno",
    subject: "Předmět:",
    subjectPh: "Předmět",
    message: "Zpráva",
    messagePh: "Vaše zpráva",
    sending: "Odesílání zprávy...",
    success: "Zpráva úspěšně odeslána!",
    error: "Chyba při odesílání zprávy:",
    links: [
      { id: 1, url: "home", text: "Doma" },
      { id: 2, url: "about", text: "O mně" },
      { id: 3, url: "qualification", text: "Kvalifikace" },
      { id: 4, url: "kranio", text: "Kraniosakrální terapie" },
      { id: 5, url: "reviews", text: "Recenze" },
      { id: 6, url: "pricelist", text: "Ceník" },
      { id: 7, url: "contact", text: "Kontakt" },
    ],
  },
};
